build.gradle
src/main/java/bio/terra/janitor/app/configuration/ApplicationConfiguration.java
src/main/java/bio/terra/janitor/app/controller/JanitorApiController.java
src/main/java/bio/terra/janitor/app/controller/UnauthenticatedApiController.java
src/main/resources/api/service_openapi.yaml
src/main/resources/api/swagger-config.json
src/test/java/bio/terra/janitor/app/controller/UnauthenticatedApiControllerTest.java

Things has changed:
- Api Controller needs to override two new method getObjectMapper and getRequest which are not needed by us. So return empty for now.
- Not so many nulls -> in our case, there will be no null get setted if we don't put value in it(see UnauthenticatedApiControllerTest.java)
- Swagger codegen seems deleted the entire target dir first. So need to move the unziped cloud_resource_uid.yaml to another directory. 
- Minor syntax change in service_api yaml file.

[CA 873] migrate from OpenApiGenerator to Swagger-Codegen for janitor service

---

build.gradle
src/main/resources/api/swagger-config.json

Seems jersery2 has a better support for oneof comepare with the default spring's one.

use jersey library which has a better oneof support

---

src/main/resources/application.properties
src/test/resources/application.properties

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=terra-kernel-k8s&minLogLevel=0&expandAll=false&timestamp=2020-08-11T17:35:40.572000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22terra-kernel-k8s%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22terra-integration%22%0Aresource.labels.namespace_name%3D%22terra-tools%22%0Alabels.k8s-pod%2Fapp%3D%22terra-crl-janitor%22%0AJanitor%20scheduling&scrollTimestamp=2020-08-10T15:17:43.589415723Z

[PF-29] fix a typo to enable the scheduler

---

src/main/java/bio/terra/janitor/service/cleanup/FlightManager.java
src/main/java/bio/terra/janitor/service/cleanup/FlightScheduler.java
src/test/java/bio/terra/janitor/service/cleanup/FlightManagerTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightSchedulerTest.java

This allows us to call the JanitorDao multiple times as a part of the same transaction.
Ref: https://www.marcobehler.com/guides/spring-transaction-management-transactional-in-depth
Use factory creation functions in tests to trim on duplication of common parameters.

PF-68 Use TransactionalTemplate in FlightManager to for JDBC transaction

---

src/main/java/bio/terra/janitor/db/JanitorDao.java
src/main/java/bio/terra/janitor/db/TrackedResourceFilter.java
src/main/java/bio/terra/janitor/service/cleanup/FlightManager.java
src/main/java/bio/terra/janitor/service/janitor/JanitorService.java
src/test/java/bio/terra/janitor/db/JanitorDaoTest.java
src/test/java/bio/terra/janitor/service/janitor/JanitorServiceTest.java

- Use TrackedResourceFilter for retrieving TrackedResources with different filters in JanitorDao.

PF-5 Add logic for duplicating resources when they are created

---

README.md
local-dev/run_local.sh
src/main/java/bio/terra/janitor/app/configuration/IamConfiguration.java
src/main/java/bio/terra/janitor/app/controller/JanitorApiController.java
src/main/java/bio/terra/janitor/common/exception/ApiException.java
src/main/java/bio/terra/janitor/common/exception/InternalServerErrorException.java
src/main/java/bio/terra/janitor/common/exception/UnauthorizedException.java
src/main/java/bio/terra/janitor/service/iam/AuthHeaderKeys.java
src/main/java/bio/terra/janitor/service/iam/AuthenticatedUserRequest.java
src/main/java/bio/terra/janitor/service/iam/AuthenticatedUserRequestFactory.java
src/main/java/bio/terra/janitor/service/iam/IamService.java
src/main/java/bio/terra/janitor/service/iam/ProxiedAuthenticatedUserRequestFactory.java
src/main/java/bio/terra/janitor/service/janitor/JanitorService.java
src/main/java/bio/terra/janitor/service/pubsub/TrackedResourceSubscriber.java
src/main/resources/application.properties
src/test/java/bio/terra/janitor/app/controller/JanitorApiControllerTest.java
src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java
src/test/java/bio/terra/janitor/service/janitor/JanitorServiceTest.java
src/test/java/bio/terra/janitor/service/pubsub/TrackedResourceSubscriberTest.java
src/test/resources/application.properties

The current implementation uses a config which contains list of admin user email address.

[PF-9] Add admin user authZ support

---

.github/workflows/master_push.yml

We have a new, more robust workflow for updating service versions in terra-helmfile (uses yq instead of regex matching). This PR configures janitor to use it.

Use terra-helmfile's new version update workflow

---

.github/workflows/master_push.yml
build.gradle

Enable the Cloud Profiler following instructions from https://cloud.google.com/profiler/docs/profiling-java.
1.  Download and extract the cloud profiler agent during jib container creation.
2.  Set cloud profiler jvm flags for configuration.
3.  Modify push github action workflow to pass service version tag as environment variable for jib.

PF-59 Add the Cloud Profiler agent to the jib build.

---

build.gradle
src/test/java/bio/terra/janitor/app/common/ResourceTypeVisitorTest.java
src/test/java/bio/terra/janitor/common/BaseIntegrationTest.java
src/test/java/bio/terra/janitor/common/BaseUnitTest.java
src/test/java/bio/terra/janitor/db/JanitorDaoTest.java
src/test/java/bio/terra/janitor/db/TrackedResourceIdTest.java
src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightManagerTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightSchedulerTest.java
src/test/java/bio/terra/janitor/service/cleanup/flight/LatchStepTest.java
src/test/java/bio/terra/janitor/service/janitor/TrackedResourceServiceTest.java
src/test/java/bio/terra/janitor/service/pubsub/TrackedResourceSubscriberTest.java

I also fixed up some of the Gradle config to show stack traces within failed tests. Not strictly related to the base test class, but it's test-related, so I thought it wasn't worth splitting into a separate cleanup PR.

[PF-103] Add a base class for unit & integration tests to further reduce duplication

---

README.md
local-dev/setup_gke_deploy.sh

The alternative git commands allow the repos to be pulled without entering a GitHub password. This worked much better for me – happy to revert if there's a preferred way for me to be setting up my GitHub creds.

[no ticket] Small documentation & GKE updates

---

src/main/java/bio/terra/janitor/app/controller/UnauthenticatedApiController.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/janitor/app/controller/UnauthenticatedApiControllerTest.java

We're removing the shutdown endpoint which puts the service in a terminating state where it will not run Stairway flights. We do not have an easy way at the moment to restrict the endpoint to k8s lifecycle operations only. Until we do, we're removing the endpoint. See PF-57.

PF-57 Temporarily remove shutdown endpoint.

---

src/main/java/bio/terra/janitor/db/CleanupFlightState.java
src/main/java/bio/terra/janitor/service/cleanup/FlightManager.java
src/main/resources/application.yml
src/test/java/bio/terra/janitor/db/BackwardsCompatibilityTest.java
src/test/java/bio/terra/janitor/db/ResourceTypeVisitorTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightManagerTest.java
src/test/resources/application-test.yml

- Handle FlightNotFound while completing flights. Add CleanupFlightState.LOST for this case.
- Add more verbose logging to FlightManager for tracked resource and flight ids.
- Fix config to stop wiping Stairway on start. Keep wiping stairway for tests on start.

PF-122 Handle FlightNotFound for "completed" cleanup flights

---

local-dev/run_local.sh
src/main/resources/db/changelog.xml
src/main/resources/db/changesets/20200925_create_resource_uid.yaml

- Add an index for resource_uid. We do a lot of searches for matching resource_uids for updating resources. Makes sense to have an index, not based on any specific benchmarking.
- Also fix some local-dev start up environment variables.

Add an index for resource_uid.

---

.github/workflows/test.yml
src/main/java/bio/terra/janitor/app/configuration/JdbcConfiguration.java
src/main/java/bio/terra/janitor/common/exception/InvalidMessageException.java
src/main/java/bio/terra/janitor/common/exception/InvalidResourceUidException.java
src/main/java/bio/terra/janitor/service/stackdriver/StackdriverExporter.java
src/test/resources/application-test.yml

Workaround to prevent connection leak while tests make heavy use of `@DirtiesContext`, see [PF-485] for more detail.
Also includes unrelated fixup of Javadoc errors, and adds javadoc to pre-merge checks (do not squash).
[PF-485]: https://broadworkbench.atlassian.net/browse/PF-485

[PF-485] Registering connection pool with JMX leads to leaks when @DirtiesContext is used.

---

build.gradle
gradle.lockfile
terra-resource-janitor-client/README.md

Includes a new field in CloudResourceUid. Bumping the version so that the janitor client library gets a new version with the updates to cloud resource uids.

PF-468 Bump janitor CRL versions.

---

build.gradle
terra-resource-janitor-client/build.gradle

CRL relies on the Janitor client and is still on Java 8. I don't think we had updated the CRL Janitor client since Janitor moved to Java 11.

PF-468 publish the janitor client for Java 8 instead of 11

---

build.gradle

Change the logging level for the profiler agent to be less spammy. Ref https://cloud.google.com/profiler/docs/profiling-java#agent_logging

PF-618 Only log errors and fatals from the cloud profiler agent.

---

README.md

Already manually grant tools janitor client-sa("crljanitor-client-tools@terra-kernel-k8s.iam.gserviceaccount.com") such permission.

[PF-656]: Add readme on how to access tools's Janitor Admin endpoint

---

src/main/java/bio/terra/janitor/app/configuration/ApplicationConfiguration.java
src/main/java/bio/terra/janitor/app/configuration/BeanNames.java
src/main/java/bio/terra/janitor/app/configuration/CrlConfiguration.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleAiNotebookInstanceCleanupFlight.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleAiNotebookInstanceCleanupStep.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBigQueryDatasetCleanupFlight.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBigQueryDatasetCleanupStep.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBigQueryTableCleanupFlight.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBigQueryTableCleanupStep.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBlobCleanupFlight.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBlobCleanupStep.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBucketCleanupFlight.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleBucketCleanupStep.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleProjectCleanupFlight.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleProjectCleanupStep.java
src/main/java/bio/terra/janitor/service/cleanup/flight/GoogleUtils.java
src/main/java/bio/terra/janitor/service/cleanup/flight/ResourceCleanupStep.java
src/main/java/bio/terra/janitor/service/cleanup/flight/UnsupportedCleanupFlight.java

Handle a special case where the project containing a notebook instance is deleted before the notebook instance is deleted. When this happens, the notebook instance will be deleted.
This does not solve the case when the project was deleted so long ago that it has been completed deleted, but I expect this to still resolve many of the recent and incoming notebook errors.
Refactor Janitor to provide CRL COW beans instead of creating them from ClientConfig each time they're needed.

PF-194 Succeed when deleting a notebook in delete requested project.

---

build.gradle
src/main/java/bio/terra/janitor/db/JanitorDao.java
src/main/java/bio/terra/janitor/db/ResourceMetadata.java
src/main/java/bio/terra/janitor/db/TrackRequest.java
src/main/java/bio/terra/janitor/db/TrackedResource.java
src/main/java/bio/terra/janitor/service/janitor/ModelUtils.java
src/main/java/bio/terra/janitor/service/janitor/TrackedResourceService.java
src/main/resources/api/service_openapi.yaml
src/main/resources/db/changelog.xml
src/main/resources/db/changesets/20210520_add_metadata.yaml
src/test/java/bio/terra/janitor/app/controller/JanitorApiControllerTest.java
src/test/java/bio/terra/janitor/db/JanitorDaoTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightManagerTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightSchedulerTest.java
src/test/java/bio/terra/janitor/service/janitor/TrackedResourceServiceTest.java

Add resource metadata to the client, internal representation, and database to allow adding additional information about a tracked resource that isn't its unique id or a label.
We will initially use this for Google project parents in order to help cleanup of projects that don't exist.

PF-194  Add resource metadata support.

---

src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java

AI notebook deletion can take a while. Give it 5 minutes before timing out the test

[no-ticket] increase the polling timeout for integratoin tests.

---

local-dev/.gitignore
local-dev/setup_gke_deploy.sh
local-dev/skaffold.yaml.template

DevOps is preparing to make some structural changes to the terra-helmfile repo; this PR updates buffer's Skaffold development workflow to be resilient to the upcoming changes. Changes include:
* Add .gitignore (shamelessly copied from WSM)
* Remove references to terra-helm
* Render manifests using terra-helmfile's `render` tool instead of invoking helm with hardcoded paths to values files
* Use Skaffold's kubectl deployment option to deploy rendered manifests
I have tested these changes by deploying `janitor` to the gmalkov personal environment.

DDO-1319 Update local dev workflow for Janitor to use `render`

---

build.gradle
gradle.lockfile

https://broadworkbench.atlassian.net/browse/PF-866, for cloud resource uid, we need to manually upgrade the version, 
Currently Janitor is broken due to invalid messages.

[no ticket] bump cloud resource uid version to have Azure changes

---

terra-resource-janitor-client/publish.sh

artifactoryPublis does not publish new packages if there is already a build target (or when there is no change in that build dir)

[no ticket] Clean test before publish

---

build.gradle
terra-resource-janitor-client/publish.sh

it seems with `clean`, we'll end up generating an empty jar
cc @yonghaoy

[no ticket] use 0.7.1

---

.github/workflows/master_push.yml

This action is failing at master due to a warning from the maintainer about a branch migration. Recommendation is to pin to `v0`.
This caused a previous GHA failure here: https://github.com/DataBiosphere/terra-resource-janitor/actions/runs/2072622858

[No ticket] Pin setup-gcloud github action to version

---

build.gradle

In #134 I updated the gradle version, but didn't update the version of some gradle plugins. The old plugins didn't work with the newer gradle, and that broke the publishing action (https://github.com/DataBiosphere/terra-resource-janitor/actions/runs/2162073055).

[PF-1531] Update gradle plugin versions

---

.github/actions/bump-skip/action.yml
.github/workflows/master_push.yml
build.gradle
settings.gradle

Janitor's `tag-build-push` workflow is currently broken because it uses `broadinstitute/github-tag-action` instead of `databiosphere/github-actions/actions/bumper`. The old action hasn't been updated since 2020, and recently broke due to git's mitigation of CVE-2022-24765 (see example workaround in https://github.com/DataBiosphere/github-actions/pull/32). Rather than fix a second bumper action, I think it makes sense to use the action currently supported by Broad devops.
This change includes:
- Swapping `broadinstitute/github-tag-action` to `databiosphere/github-actions/actions/bumper`, plus a handful of related changes inside the `tag-build-push` workflow inspired by [WSM's workflow](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/.github/workflows/tag-publish.yml).
- …

[PF-1557] Follow WSM pattern for publishing

---

.github/workflows/master_push.yml

This action updates the version number in `settings.gradle`. In order to merge this change to the main branch without reviews, this must be done as an admin (in this case Broadbot). I've already set up the BROADBOT_TOKEN secret via the Vault -> GHA secrets terraform. Hopefully this is the last change needed to fix publishing!

[PF-1557] Run bump + tag action as broadbot

---

.github/workflows/master_push.yml
.github/workflows/test.yml

Per documentation at https://github.com/actions/checkout, the `checkout` action persists a git token and it seems like this overrides the token provided to the `bumper` action, causing the bumptagbot commit to fail (see "Bump the tag to a new version" [section of GHA run](https://github.com/DataBiosphere/terra-resource-janitor/runs/6067290741?check_suite_focus=true)). 
This also stops tests from running on version bump commits, as they'll always be the same as the real commit which caused them.

[PF-1557] Checkout repo as Broadbot in build-tag-publish workflow

---

src/main/java/bio/terra/janitor/app/configuration/WorkspaceManagerConfiguration.java
src/main/java/bio/terra/janitor/service/workspace/WorkspaceManagerService.java
src/main/resources/application.yml
src/main/resources/static/service_openapi.yaml

Mapping identifiers to WSM urls meant we needed to keep hardcoded strings in sync across services, using urls in requests avoids this. However, we're still using a config-based allowlist, which prevents users from forcing Janitor to call arbitrary urls.
See usage in https://github.com/DataBiosphere/terra-cli/pull/246

[PF-883] Store WSM url allowlist in Janitor config instead of using identifiers

---

.github/workflows/master_push.yml
.github/workflows/test.yml

(Same situation as https://github.com/DataBiosphere/terra-resource-buffer/pull/244)
These workflows are masking secrets incorrectly, the masking needs to happen before setting them as output. If this workflow is run with debug logging (which it isn't), the current pattern will leak secrets.

Fix GHA secret masking

---

src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java

This test started failing ~a week ago, it seems like Azure is returning a different error code. See failed runs: https://github.com/DataBiosphere/terra-resource-janitor/actions/runs/2804596833 and https://github.com/DataBiosphere/terra-resource-janitor/actions/runs/2848072566

[PF-1731] Fix broken test

---

gradle/jib.gradle

Problem statement - Standard eclipse temurin images potentially have app-security concerns
Fix - use the broad app-security-approved images from https://github.com/broadinstitute/dsp-appsec-blessed-images
No further checks were performed since the major version is the same, minor version is a downgrade

[PF-940] Use broad-appsec-blessed JRE image

---

.github/workflows/master_push.yml
local-dev/skaffold.yaml.template

This needs to be merged (and a new image needs to be published) before the equivalent helmfile change can merge. This also fixes the publish workflow, equivalent to https://github.com/DataBiosphere/terra-resource-buffer/pull/259

[PF-2168] Move from terra-kernel-k8s to broad-dsp-gcr-public

---

.github/workflows/test.yml

Only run PR checks when the PR targets primary/default branch
currently, all PRs (irrespective of the branch they target) automatically trigger PR checks. This is unnecessary and may cause the checks to be queued up on GitHub runner.
ref - 
- https://github.com/DataBiosphere/terra-workspace-manager/pull/1061
- https://broadworkbench.atlassian.net/browse/PF-2478

[PF-2478] Only run checks when PR targets default branch

---

.github/workflows/master_push.yml

The existing `repository-dispatch` based notification flow is broken, and publishing workflows have been broken for several weeks (though only one real PR was added in that time).
Janitor is not deployed in Broad dev, so I'm not including the "push to dev" step in this workflow.

[PF-2511] Fix workflow to notify Broad devops

---

.github/actions/bump-skip/action.yml
.github/workflows/master_push.yml
.github/workflows/test.yml

Replace deprecated commands in GH actions & workflows.
- use actions/setup-java@v3 instead of v2
- use actions/checkout@v3 instead of v2
- use actions/cache@v3 instead of v2
- use actions/upload-artifact@v3 instead of v2
- use setup-node@v3 instead of v2
- replace 'set-output' command

[TERRA-434] Replace deprecated commands in GH actions & workflows

---

.github/workflows/master_push.yml
gradle/publishing.gradle

This adds an additional step to automatically publish a new client library version every time a PR is merged to main. This also fixes an issue with the `artifactoryPublish` action, which wasn't working properly

Automatically publish client library on merge to main

---

src/main/java/bio/terra/janitor/service/cleanup/FlightManager.java
src/main/java/bio/terra/janitor/service/cleanup/FlightScheduler.java
src/main/java/bio/terra/janitor/service/cleanup/MetricsHelper.java
src/main/java/bio/terra/janitor/service/cleanup/MetricsViews.java
src/test/java/bio/terra/janitor/service/cleanup/FlightSchedulerTest.java
src/test/java/bio/terra/janitor/service/cleanup/MetricsHelperTest.java

https://broadworkbench.atlassian.net/browse/PF-2979
Follow-up to https://github.com/DataBiosphere/terra-resource-janitor/pull/171
The OpenTelemetry -> Google export is working, but I discovered some issues when looking at metrics.
1. I was interpreting `trackedResourceCount` as a counter when it should be a gauge, leading to weirdness in the dashboards.
2. Janitor doesn't actually have counters for resource cleanup submissions and completions -- just gauges and timing histograms. So I added some counters to be able to see rates of resource cleanups over time. The gauges are less useful IMO because there are so many DONE records.

PF-2979 followup: fix metrics

---

src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java

Disable integration tests.
Azure integration tests are failing because we have deleted the MRG in which the tests try to run.
GCP integration tests are failing because we have deleted cloud resources (SAs, pubsub topics, etc) which the tests need to run.
Turning off the integration tests allows us to focus on upgrading Postgres. After the Postgres upgrade, we can revisit if we want to re-enable the tests or delete them entirely.

CORE-250: disable azure integration tests

---

.github/workflows/test.yml
local-dev/local-postgres-init.sql
local-dev/run_postgres.sh

Upgrades unit tests and local development to Postgres 16.6.
The unit tests passed 10 times in a row in GHA for this PR (I re-ran it manually). I do see intermittent unit test failures when running locally - but they're not consistent, and different test cases fail on different runs. I am inclined to write that off as an environmental issue. When running locally, unit tests pass about half the time with only one test causing each failure.
We _could_ go all the way to Postgres 17. However, Postgres 16 is the GCP default (see [here](https://cloud.google.com/sql/docs/postgres/db-versions)) and in my opinion this is not the place to push the envelope, nor would Janitor particularly benefit from the newer version. Postgres 16 does not hit extended support charges until February 1, 2029.

CORE-250: upgrade Postgres to 16.6

---

.github/workflows/master_push.yml
.github/workflows/test.yml

* Use the latest versions of github actions
* Use `setup-java`'s cache for gradle instead of an explicit call to `actions/cache`
* remove an extraneous/unknown input on `google-github-actions/auth`

CORE-69: update to latest github actions; action cleanup

---

.github/workflows/test.yml
local-dev/render-config.sh
src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java
src/test/java/bio/terra/janitor/integration/common/configuration/TestConfiguration.java
src/test/resources/application-integration.yml

Ticket: https://broadworkbench.atlassian.net/browse/CORE-265
The app-sa, client-sa and pubsub queue in the old `toolsalpha` env are now replaced with new ones that were [terraformed](https://github.com/broadinstitute/terraform-ap-deployments/pull/1800) in the `broad-dsde-qa` project. This allows us to re-enable all of the integration tests for GCP resources.

[CORE-265] Replace toolsalpha with qa env

---

.github/workflows/test.yml
src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java
src/test/java/bio/terra/janitor/integration/common/configuration/TestConfiguration.java
src/test/resources/application-integration.yml

**Ticket:** https://broadworkbench.atlassian.net/browse/CORE-265
**Background:**
The Azure resources required for the integration tests to run were deleted, causing them to fail. Since we plan on removing support for Azure, delete these disabled integration tests and remove any Azure-specific test configs (since they currently point to non-existent resources).

[CORE-265] Remove disabled Azure integration tests

---

src/main/resources/application.yml

https://broadworkbench.atlassian.net/browse/CORE-401
This disables the OpenTelemetry Logback integration via a simple config switch. See https://opentelemetry.io/docs/zero-code/java/spring-boot-starter/out-of-the-box-instrumentation/ for settings.
The otel/logback integration was not working and would repeatedly log errors:
```
Failed to export logs. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4318
```
This PR should quell those errors.
Information about the otel/logback integration: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library

CORE-401: disable otel logback integration

---

src/test/java/bio/terra/janitor/integration/TrackResourceIntegrationTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightManagerTest.java
src/test/java/bio/terra/janitor/service/cleanup/FlightSchedulerTest.java
src/test/java/bio/terra/janitor/service/iam/IamServiceTest.java

#196, as part of upgrading terra-common-lib, upgraded Spring Boot.
The newer version of Spring Boot deprecates `@MockBean` in favor of `@MockitoBean` and logs warnings during compilation when `@MockBean` is used.
This PR switches all usages of `@MockBean` to `@MockitoBean`.

CORE-391: MockBean -> MockitoBean

---

build.gradle

JIRA ticket https://broadworkbench.atlassian.net/browse/DDO-4134 
**Summary of changes**
Updated the artifact source for this service to read artifacts from Google Artifact Registry instead of JFrog.
**What**
Modified the config to pull artifacts from GAR. No publishing changes were made.
**Why**
This is part of Phase 2 of the artifact migration effort to deprecated JFrog and consolidate artifacts in GAR.
**Testing these changes**
Relied on passing CI checks and tests. Artifact reading-related issues are expected to surface as pipeline failures. For example these jobs [here](https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/15309876591/job/43071753325?pr=222) and [here](https://github.com/DataBiosphere/leonardo/actions/runs/15324072477/job/43114134405?pr=4858 …

DDO-4134 read from google artifact registry

---

.github/workflows/master_push.yml
gradle/publishing.gradle
settings.gradle
terra-resource-janitor-client/build.gradle
terra-resource-janitor-client/publish.sh

https://broadworkbench.atlassian.net/browse/DDO-4338
Migrate artifact publishing from JFrog to Google Artifact Registry.
Note:
> The two failing tests (`subscribeAndCleanupResource_googleNotebookInstance` and `subscribeAndCleanupResource_alreadyDeletedGoogleNotebookInstance`) are failing because Vertex AI Workbench user-managed notebooks have been deprecated.
> 
> The recommended approach is to migrate these tests to use Vertex AI Workbench managed notebooks. See the [migration guide](https://cloud.google.com/vertex-ai/docs/workbench/user-managed/migrate-to-instances) for details.
> 
> To unblock the GAR migration work (which is unrelated to the test failure), I've created [DDO-4341](https://broadworkbench.atlassian.net/browse/DDO-4341) to address the issue at a later time.
> 
> …

DDO-4338 publish to gar
